name: dicecash
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  animations: ^2.0.2
  cloud_firestore: ^4.8.2
  font_awesome_flutter: ^10.1.0
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^4.6.3
  get: ^4.6.3
#  shared_preferences: ^2.0.15
  google_sign_in: ^5.3.1
  google_fonts: ^3.0.1
  future_progress_dialog: ^0.2.0
  lottie: ^1.3.0
  flutter_custom_tabs: ^1.0.4
  emojis: ^0.9.9
  assets_audio_player: ^3.0.4+3
  fluttertoast: ^8.0.9
  dotted_border: ^2.0.0+2
  social_share: ^2.2.1
  logger: ^1.1.0
  stacked: ^3.4.1
  stacked_services: ^1.2.0
  streaming_shared_preferences: ^2.0.0
  flutter_native_splash: ^2.1.6
  enum_to_string: ^2.0.1
  firebase_core: ^2.14.0
  url_launcher: ^6.1.3
  timeago: ^3.2.2
  overlay_support: ^1.2.1
  flutter_polygon: ^0.2.0
  cloud_functions: ^4.3.3
  provider: ^6.0.4
  flutter_tts: ^3.5.3
  video_player: ^2.1.4
  get_it: ^7.1.3
  cached_network_image: ^3.0.0
  simple_animations: ^1.3.3
  scrollable_positioned_list: ^0.1.10


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_native_splash:
  # color: "#42a5f5"
  background_image: "assets/logo/splash.png"


flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - assets/illustration/
    - assets/images/
    - assets/dice/
    - assets/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/bold_italic.ttf
        - asset: assets/fonts/bold.ttf
          weight: 700
        - asset: assets/fonts/italic.ttf
          style: italic
        - asset: assets/fonts/regular.ttf

